// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.SqlServerDbContext
{
    [DbContext(typeof(MainDbContext.SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModels.AddressDbm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostCode")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.Property<string>("StreetName")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DbModels.AttractionDbm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("DbModels.CityDbm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DbModels.CommentDbm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DbModels.CountryDbm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DbModels.RatingDbm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("DbModels.UserDbm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DbModels.AddressDbm", b =>
                {
                    b.HasOne("DbModels.CityDbm", "CityDbm")
                        .WithMany("AddressesDbm")
                        .HasForeignKey("CityId");

                    b.Navigation("CityDbm");
                });

            modelBuilder.Entity("DbModels.AttractionDbm", b =>
                {
                    b.HasOne("DbModels.AddressDbm", "AddressDbm")
                        .WithMany("AttractionsDbm")
                        .HasForeignKey("AddressId");

                    b.Navigation("AddressDbm");
                });

            modelBuilder.Entity("DbModels.CityDbm", b =>
                {
                    b.HasOne("DbModels.CountryDbm", "CountryDbm")
                        .WithMany("CitiesDbm")
                        .HasForeignKey("CountryId");

                    b.Navigation("CountryDbm");
                });

            modelBuilder.Entity("DbModels.CommentDbm", b =>
                {
                    b.HasOne("DbModels.AttractionDbm", "AttractionDbm")
                        .WithMany("CommentsDbm")
                        .HasForeignKey("AttractionId");

                    b.HasOne("DbModels.UserDbm", "UserDbm")
                        .WithMany("CommentsDbm")
                        .HasForeignKey("UserId");

                    b.Navigation("AttractionDbm");

                    b.Navigation("UserDbm");
                });

            modelBuilder.Entity("DbModels.RatingDbm", b =>
                {
                    b.HasOne("DbModels.AttractionDbm", "AttractionDbm")
                        .WithMany("RatingsDbm")
                        .HasForeignKey("AttractionId");

                    b.HasOne("DbModels.UserDbm", "UserDbm")
                        .WithMany("RatingsDbm")
                        .HasForeignKey("UserId");

                    b.Navigation("AttractionDbm");

                    b.Navigation("UserDbm");
                });

            modelBuilder.Entity("DbModels.AddressDbm", b =>
                {
                    b.Navigation("AttractionsDbm");
                });

            modelBuilder.Entity("DbModels.AttractionDbm", b =>
                {
                    b.Navigation("CommentsDbm");

                    b.Navigation("RatingsDbm");
                });

            modelBuilder.Entity("DbModels.CityDbm", b =>
                {
                    b.Navigation("AddressesDbm");
                });

            modelBuilder.Entity("DbModels.CountryDbm", b =>
                {
                    b.Navigation("CitiesDbm");
                });

            modelBuilder.Entity("DbModels.UserDbm", b =>
                {
                    b.Navigation("CommentsDbm");

                    b.Navigation("RatingsDbm");
                });
#pragma warning restore 612, 618
        }
    }
}
